#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Next generation astrophotography.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Leon Jungemeyer                               
your_link                                 : https://emilbaehr.com                     
your_city                                 : Karlsruhe, Germany                                
email_address                             : leon.jungemeyer@me.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : ju-leon
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Advanced stacking
    description                           : Take hundreds of images with the press of a button, automatically stack and align them to get the perfect picture. 
    fontawesome_icon_name                 : layer-group
    
  - title                                 : Smart image processing
    description                           : AI enhanced algorithms make sure that the stars in your image pop while keeping noise to a minumum.
    fontawesome_icon_name                 : star

  - title                                 : Automatic timelapse
    description                           : While generating stunning pictures, a beautiful timelapse of the moving night sky is created.
    fontawesome_icon_name                 : fast-forward

  - title                                 : Professional editing
    description                           : Advanced tools let you customise your shot to truly match your style.
    fontawesome_icon_name                 : tools

  - title                                 : Ready when you are
    description                           : No setup required. Hit the shutter, sit back and wait for the perfect photo.
    fontawesome_icon_name                 : campground
  
  - title                                 : Stabilise your phone
    description                           : Use a tripod or lean your phone against a solid object to get the best results.
    fontawesome_icon_name                 : hat-wizard


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/background.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#209ce8"
cover_overlay_transparency                : 0.2

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

theme: jekyll-theme-cayman